name: Docker Build and Publish NuGet Package

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: [ self-hosted ]
    
    steps:
      - uses: actions/checkout@v3

      - name: Increment version in .csproj
        id: inc-version
        run: |
          VERSION_FILE="version.txt"
          CS_PROJ_FILE="BEAUTIFY_PACKAGES.SHARE/BEAUTIFY_PACKAGES.SHARE.csproj"
          
          if [ ! -f "$VERSION_FILE" ]; then
            echo "version.txt not found. Creating with default 1.0.0"
            echo "1.0.0" > "$VERSION_FILE"
          fi
          
          CURRENT_VERSION=$(cat "$VERSION_FILE")
          echo "Current version: $CURRENT_VERSION"

          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"

          if [ "$PATCH" -lt 10 ]; then
            PATCH=$((PATCH + 1))
          else
            PATCH=0
            MINOR=$((MINOR + 1))
          fi

          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          echo "New version: $NEW_VERSION"

          sed -i "s#<Version>$CURRENT_VERSION</Version>#<Version>$NEW_VERSION</Version>#" "$CS_PROJ_FILE"

          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
        
        
        
      - name: Commit and push updated version
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add version.txt BEAUTIFY_PACKAGES.SHARE/*.csproj
          git commit -m "Increment version to ${{ steps.versioning.outputs.new_version }}"
          git push origin main
      
      
      - name: Build Docker Image
        run: docker build -t beautify_packages:latest -f BEAUTIFY_PACKAGES.SHARE/Dockerfile .

      - name: Copy NuGet package from Docker container
        run: |
          docker create --name temp beautify_packages:latest
          docker cp temp:/app/nupkg ./nupkg
          docker rm temp

      - name: Push to NuGet
        env:
          DOTNET_CLI_HOME: /tmp  # Set it to a writable location
        run: |
          dotnet nuget push ./nupkg/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: ./nupkg/*.nupkg

      - name: Cleanup Docker
        run: docker system prune -f
