name: Docker Build and Publish NuGet Package

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: [ self-hosted ]
    
    steps:
      - uses: actions/checkout@v3

      - name: Increment version in .csproj
        id: inc-version
        run: |
          # Path to your .csproj file (adjust name as needed)
          CS_PROJ_FILE="BEAUTIFY_PACKAGES.SHARE/BEAUTIFY_PACKAGES.SHARE.csproj"

          # Extract current version (assuming <Version>X.Y.Z</Version>)
          CURRENT_VERSION=$(grep "<Version>" "$CS_PROJ_FILE" | sed -E 's/.*<Version>([0-9]+\.[0-9]+\.[0-9]+)<\/Version>.*/\1/')
          echo "Current version: $CURRENT_VERSION"

          # Split into major, minor, patch
          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"

          # Increment logic: If patch < 10, increment patch. Otherwise, reset patch to 0 and increment minor.
          if [ "$PATCH" -lt 10 ]; then
            PATCH=$((PATCH + 1))
          else
            PATCH=0
            MINOR=$((MINOR + 1))
          fi

          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          echo "New version: $NEW_VERSION"

          # Update version in .csproj
          sed -i "s#<Version>$CURRENT_VERSION</Version>#<Version>$NEW_VERSION</Version>#" "$CS_PROJ_FILE"

          # Expose as output for future steps (e.g., if you need it anywhere else)
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
      
      - name: Build Docker Image
        run: docker build -t beautify_packages:latest -f BEAUTIFY_PACKAGES.SHARE/Dockerfile .

      - name: Copy NuGet package from Docker container
        run: |
          docker create --name temp beautify_packages:latest
          docker cp temp:/app/nupkg ./nupkg
          docker rm temp

      - name: Push to NuGet
        env:
          DOTNET_CLI_HOME: /tmp  # Set it to a writable location
        run: |
          dotnet nuget push ./nupkg/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: ./nupkg/*.nupkg

      - name: Cleanup Docker
        run: docker system prune -f
